"""
TOML Block Importer - Import CMS-exported TOML sites back into Hugo CMS.

This importer handles the TOML frontmatter format with [[main_blocks]] arrays
that is generated by the CMS when publishing sites.

Usage:
    from hugo.toml_importer import import_toml_site
    website = import_toml_site('/path/to/hugo/output', 'Site Name', 'site-slug')
"""
import os
import re
import toml
from pathlib import Path
from django.db import transaction
from django.conf import settings
from .models import Website, Page, BlockInstance, BlockDefinition
import shutil


def parse_toml_frontmatter(content):
    """
    Parse TOML frontmatter from a markdown file.
    Returns (frontmatter_dict, body_content).
    """
    if content.startswith('+++'):
        # Find the closing +++
        end_marker = content.find('+++', 3)
        if end_marker != -1:
            toml_content = content[3:end_marker]
            body = content[end_marker + 3:].strip()
            try:
                frontmatter = toml.loads(toml_content)
                return frontmatter, body
            except Exception as e:
                print(f"TOML parse error: {e}")
                return {}, content
    return {}, content


def copy_assets(hugo_root, website_slug):
    """
    Copy static assets from Hugo site to CMS media directory.
    """
    static_dir = Path(hugo_root) / 'static'
    public_dir = Path(hugo_root) / 'public'
    
    target_dir = Path(settings.MEDIA_ROOT) / 'uploads' / website_slug
    target_dir.mkdir(parents=True, exist_ok=True)
    
    # Copy from static/
    if static_dir.exists():
        for item in static_dir.glob('**/*'):
            if item.is_file():
                rel_path = item.relative_to(static_dir)
                dest = target_dir / rel_path
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, dest)
    
    # Copy media from public/media/ if exists
    media_dir = public_dir / 'media'
    if media_dir.exists():
        for item in media_dir.glob('**/*'):
            if item.is_file():
                rel_path = item.relative_to(media_dir)
                dest = target_dir / rel_path
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, dest)
    
    return f"/media/uploads/{website_slug}/"


def load_css(hugo_root):
    """
    Load custom CSS from the Hugo site.
    """
    css_paths = [
        Path(hugo_root) / 'static' / 'css' / 'custom.css',
        Path(hugo_root) / 'assets' / 'css' / 'custom.css',
        Path(hugo_root) / 'static' / 'css' / 'main.css',
    ]
    
    for css_path in css_paths:
        if css_path.exists():
            with open(css_path, 'r') as f:
                return f.read()
    
    return ''


def create_blocks_from_toml(blocks_data, page, website, parent=None, placement_key='main'):
    """
    Recursively create BlockInstance records from TOML block arrays.
    
    Args:
        blocks_data: List of block dicts from TOML (e.g., frontmatter['main_blocks'])
        page: The Page instance (only for root-level blocks)
        website: The Website instance
        parent: Parent BlockInstance (for nested blocks)
        placement_key: Placement key for the blocks
    """
    created_blocks = []
    
    for i, block_data in enumerate(blocks_data):
        block_type = block_data.get('type')
        if not block_type:
            continue
        
        # --- Special handling: Detect flex_columns from row+columns ---
        # If this is a row with flex_mode=true and all children are columns with width_percent,
        # convert it back to flex_columns
        child_blocks = block_data.get('blocks', [])
        if block_type == 'row' and block_data.get('flex_mode'):
            all_columns_with_width = True
            width_percents = []
            
            for child in child_blocks:
                if child.get('type') != 'column' or not child.get('width_percent'):
                    all_columns_with_width = False
                    break
                width_percents.append(child.get('width_percent'))
            
            if all_columns_with_width and width_percents:
                # Convert to flex_columns
                block_type = 'flex_columns'
                try:
                    definition = BlockDefinition.objects.get(id='flex_columns')
                except BlockDefinition.DoesNotExist:
                    print("WARNING: flex_columns definition not found, using row instead")
                    definition = BlockDefinition.objects.get(id='row')
                    block_type = 'row'
                
                if block_type == 'flex_columns':
                    # Create flex_columns block with col_widths param
                    params = {
                        'col_widths': ', '.join(width_percents),
                        'css_classes': block_data.get('css_classes', '')
                    }
                    
                    instance = BlockInstance.objects.create(
                        definition=definition,
                        page=page if parent is None else None,
                        website=website,
                        parent=parent,
                        placement_key=placement_key,
                        sort_order=i,
                        params=params
                    )
                    created_blocks.append(instance)
                    
                    # Create children with placement_key = col_0, col_1, etc.
                    for col_idx, col_data in enumerate(child_blocks):
                        col_children = col_data.get('blocks', [])
                        if col_children:
                            create_blocks_from_toml(
                                col_children,
                                page=None,
                                website=website,
                                parent=instance,
                                placement_key=f'col_{col_idx}'
                            )
                    
                    continue  # Skip normal handling
        
        # Normal block handling
        try:
            definition = BlockDefinition.objects.get(id=block_type)
        except BlockDefinition.DoesNotExist:
            print(f"WARNING: Block definition '{block_type}' not found, skipping")
            continue
        
        # Extract params (everything except 'type' and 'blocks')
        params = {}
        for key, value in block_data.items():
            if key in ('type', 'blocks'):
                continue
            params[key] = value
        
        # --- Special handling: carousel slides ---
        # Carousel stores slides in params.slides as JSON, not as BlockInstance children
        # Must be done BEFORE creating the instance so params.slides is saved
        if block_type == 'carousel' and child_blocks:
            import uuid
            slides = []
            for slide_idx, slide_child in enumerate(child_blocks):
                slide_id = f'slide_{uuid.uuid4().hex[:16]}'
                slide = {
                    'id': slide_id,
                    'children': [{
                        'id': str(uuid.uuid4()),
                        'type': slide_child.get('type'),
                        'params': {k: v for k, v in slide_child.items() if k not in ('type', 'blocks')},
                        'children': None,  # Carousel slides can't have nested children in current implementation
                        'placement_key': f'carousel_slide_pending_{slide_idx}',  # Will be updated after instance creation
                        'parent_id': None,  # Will be updated after instance creation
                        'sort_order': 0
                    }]
                }
                slides.append(slide)
            
            params['slides'] = slides
            # Don't recursively create children for carousel - they're in params now
            child_blocks = []
        
        # Create the block instance
        instance = BlockInstance.objects.create(
            definition=definition,
            page=page if parent is None else None,
            website=website,
            parent=parent,
            placement_key=placement_key,
            sort_order=i,
            params=params
        )
        created_blocks.append(instance)
        
        # Update carousel slide metadata with actual instance ID
        if block_type == 'carousel' and 'slides' in params:
            for slide_idx, slide in enumerate(params['slides']):
                for child in slide.get('children', []):
                    child['placement_key'] = f'carousel_slide_{instance.id}_{slide_idx}'
                    child['parent_id'] = str(instance.id)
            # Save the updated params
            instance.params = params
            instance.save()
        
        # Recursively create child blocks (for non-carousel containers)
        if child_blocks:
            # Determine child placement key based on parent type
            child_placement = 'blocks'
            if block_type == 'carousel':
                child_placement = 'slide'  # Won't reach here due to above handling
            elif block_type == 'row':
                child_placement = 'column'
            
            create_blocks_from_toml(
                child_blocks, 
                page=None, 
                website=website, 
                parent=instance, 
                placement_key=child_placement
            )
    
    return created_blocks


@transaction.atomic
def import_toml_site(hugo_root, website_name, website_slug):
    """
    Import a Hugo site with TOML frontmatter into Hugo CMS.
    
    This supports the TOML block array format:
        +++
        title = "Page Title"
        [[main_blocks]]
        type = "hero"
        title = "Welcome"
        [[main_blocks]]
        type = "text"  
        content = "Hello"
        +++
    
    Args:
        hugo_root: Path to the Hugo site root directory
        website_name: Name for the new CMS website
        website_slug: URL slug for the new website
    
    Returns:
        Website instance
    """
    hugo_path = Path(hugo_root)
    
    if not hugo_path.exists():
        raise ValueError(f"Hugo site path does not exist: {hugo_root}")
    
    # Load custom CSS
    custom_css = load_css(hugo_root)
    
    # Create website
    website = Website.objects.create(
        name=website_name,
        slug=website_slug,
        custom_css=custom_css
    )
    
    # Copy assets
    media_url_base = copy_assets(hugo_root, website_slug)
    
    # Parse content files
    content_dir = hugo_path / 'content'
    if not content_dir.exists():
        print(f"No content directory found at {content_dir}")
        return website
    
    # Find all markdown files
    md_files = list(content_dir.glob('**/*.md'))
    
    # First pass: collect all frontmatter to check for global headers/footers
    all_frontmatter = []
    all_headers = []
    all_footers = []
    for md_file in md_files:
        with open(md_file, 'r') as f:
            content = f.read()
        frontmatter, body = parse_toml_frontmatter(content)
        if frontmatter:
            all_frontmatter.append((md_file, frontmatter, body))
            header_blocks = frontmatter.get('header_blocks', [])
            if header_blocks:
                all_headers.append(header_blocks)
            footer_blocks = frontmatter.get('footer_blocks', [])
            if footer_blocks:
                all_footers.append(footer_blocks)
    
    # Import global header if present and consistent
    if all_headers:
        # Check if all headers are the same
        import json
        headers_json = [json.dumps(h, sort_keys=True) for h in all_headers]
        if len(set(headers_json)) == 1:
            # All pages have the same header - import as global
            print(f"Importing global header with {len(all_headers[0])} blocks")
            create_blocks_from_toml(
                all_headers[0],
                page=None,  # Global header
                website=website,
                parent=None,
                placement_key='header'
            )
        else:
            print(f"WARNING: Pages have different headers. CMS only supports global headers.")
            print(f"  Using header from first page. {len(set(headers_json))} unique headers found.")
            # Use the first header as global
            create_blocks_from_toml(
                all_headers[0],
                page=None,
                website=website,
                parent=None,
                placement_key='header'
            )
    
    # Import global footer if present and consistent
    if all_footers:
        # Check if all footers are the same
        import json
        footers_json = [json.dumps(f, sort_keys=True) for f in all_footers]
        if len(set(footers_json)) == 1:
            # All pages have the same footer - import as global
            print(f"Importing global footer with {len(all_footers[0])} blocks")
            create_blocks_from_toml(
                all_footers[0],
                page=None,  # Global footer
                website=website,
                parent=None,
                placement_key='footer'
            )
        else:
            print(f"WARNING: Pages have different footers. CMS only supports global footers.")
            print(f"  Using footer from first page. {len(set(footers_json))} unique footers found.")
            # Use the first footer as global
            create_blocks_from_toml(
                all_footers[0],
                page=None,
                website=website,
                parent=None,
                placement_key='footer'
            )
    
    # Second pass: create pages and import blocks
    for md_file, frontmatter, body in all_frontmatter:
        # Determine page slug from file path
        relative_path = md_file.relative_to(content_dir)
        
        if md_file.name == '_index.md':
            if md_file.parent == content_dir:
                slug = '/'
            else:
                slug = '/' + str(relative_path.parent)
        elif md_file.name == 'index.md':
            slug = '/' + str(relative_path.parent)
        else:
            slug = '/' + str(relative_path.with_suffix(''))
        
        # Create page
        page = Page.objects.create(
            website=website,
            title=frontmatter.get('title', md_file.stem.replace('-', ' ').title()),
            slug=slug,
            layout=frontmatter.get('layout', 'single'),
            description=frontmatter.get('description', ''),
            status='draft'
        )
        
        # Get blocks from frontmatter
        main_blocks = frontmatter.get('main_blocks', [])
        
        if main_blocks:
            create_blocks_from_toml(
                main_blocks,
                page=page,
                website=website,
                parent=None,
                placement_key='main'
            )
        
        # Handle other block zones (sidebar_blocks only)
        # Note: header_blocks and footer_blocks are handled globally above
        for zone_key in ['sidebar_blocks']:
            zone_blocks = frontmatter.get(zone_key, [])
            if zone_blocks:
                # Remove '_blocks' suffix for placement key
                placement = zone_key.replace('_blocks', '')
                create_blocks_from_toml(
                    zone_blocks,
                    page=page,
                    website=website,
                    parent=None,
                    placement_key=placement
                )
        
        print(f"Imported page: {page.title} ({slug}) with {len(main_blocks)} blocks")
    
    return website

