
baseURL = 'https://test-site.monu.dev'
languageCode = 'en-us'
title = 'Test Site'
theme = []

[params]
    description = ''
    theme_preset = 'default'
    
[mediaTypes]
[mediaTypes."text/css"]
    suffixes = ["css"]
            