
baseURL = 'https://strippin-v2.monu.dev'
languageCode = 'en-us'
title = 'Strippin Dippin Chicken V2'
theme = []

[params]
    description = ''
    theme_preset = 'valentine'
    
[build]
    writeStats = true

[[build.cachebusters]]
    source = "hugo_stats.json"
    target = "styles.css"
    
[mediaTypes]
[mediaTypes."text/css"]
    suffixes = ["css"]
            