
baseURL = 'https://default.monu.dev'
languageCode = 'en-us'
title = 'Default Site'
theme = []

[params]
    description = ''
    theme_preset = 'default'
    
[mediaTypes]
[mediaTypes."text/css"]
    suffixes = ["css"]
            