
baseURL = 'https://mad-taco-az.monu.dev'
languageCode = 'en-us'
title = 'Mad Taco AZ'
theme = []

[params]
    description = ''
    theme_preset = 'black'
    
[build]
    writeStats = true

[[build.cachebusters]]
    source = "hugo_stats.json"
    target = "styles.css"
    
[mediaTypes]
[mediaTypes."text/css"]
    suffixes = ["css"]
            