# Generated by Django 5.2.8 on 2025-11-26 02:27

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDefinition',
            fields=[
                ('id', models.CharField(help_text="Unique key like 'hero' or 'youtube'", max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Lucide icon name (e.g., 'layout')", max_length=50)),
                ('has_visual_preview', models.BooleanField(default=False, help_text='Does the frontend have a specific renderer for this?')),
                ('default_params', models.JSONField(default=dict, help_text='Default values when a user drags this block in')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(help_text="URL path (e.g., '/about')", max_length=200, unique=True)),
                ('layout', models.CharField(default='single', help_text='Hugo layout template name', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement_key', models.CharField(help_text="The zone ('header'/'footer') or column key ('col_1', 'col_2') it belongs to.", max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('params', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='hugo.blockdefinition')),
                ('parent', models.ForeignKey(blank=True, help_text="Link to the parent block (e.g., a 'flex_columns' instance).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hugo.blockinstance')),
                ('page', models.ForeignKey(blank=True, help_text='Link to Page if this is a main content block.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_blocks', to='hugo.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['page', 'placement_key', 'sort_order'], name='hugo_blocki_page_id_16ae48_idx'), models.Index(fields=['parent', 'placement_key', 'sort_order'], name='hugo_blocki_parent__0a99f0_idx')],
            },
        ),
    ]
