# Generated by the CMS initialization logic.
from django.db import migrations
import uuid

def create_initial_data(apps, schema_editor):
    """
    Populates BlockDefinition, Page, and BlockInstance models 
    to match the initial state of the Vue frontend.
    """
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    Page = apps.get_model('hugo', 'Page')
    BlockInstance = apps.get_model('hugo', 'BlockInstance')

    # --- 1. BLOCK DEFINITIONS ---
    
    # We use a mapping similar to the Vue file to ensure consistency
    BLOCK_DEFINITIONS_DATA = {
        'hero': {
            'label': 'Hero Section',
            'icon': 'layout',
            'has_visual_preview': True,
            'default_params': { 
                'title': 'Welcome Home', 
                'subtitle': 'Start your journey here', 
                'bgImage': 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&q=80' 
            }
        },
        'text': {
            'label': 'Text Block',
            'icon': 'type',
            'has_visual_preview': True,
            'default_params': { 'content': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' }
        },
        'image': {
            'label': 'Image',
            'icon': 'image',
            'has_visual_preview': True,
            'default_params': { 'src': 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80', 'caption': 'A beautiful view' }
        },
        'columns': {
            'label': '3 Columns',
            'icon': 'columns',
            'has_visual_preview': True,
            'default_params': { 'col1': 'Feature A', 'col2': 'Feature B', 'col3': 'Feature C' }
        },
        'markdown': {
            'label': 'Markdown',
            'icon': 'file-text',
            'has_visual_preview': True,
            'default_params': { 'md': '## Hello World\nThis is **markdown** content.' }
        },
        # Arbitrary/Generic Blocks
        'youtube': {
            'label': 'YouTube Embed',
            'icon': 'video',
            'has_visual_preview': False,
            'default_params': { 'videoId': 'dQw4w9WgXcQ', 'title': 'My Video' }
        },
        'alert': {
            'label': 'Alert Box',
            'icon': 'alert-triangle',
            'has_visual_preview': False,
            'default_params': { 'type': 'warning', 'message': 'This is an important alert message.' }
        },
        'quote': {
            'label': 'Blockquote',
            'icon': 'type',
            'has_visual_preview': False,
            'default_params': { 'text': 'Design is intelligence made visible.', 'author': 'Alina Wheeler' }
        }
    }

    definitions_map = {}
    for block_id, data in BLOCK_DEFINITIONS_DATA.items():
        definition = BlockDefinition.objects.create(
            id=block_id,
            label=data['label'],
            icon=data['icon'],
            has_visual_preview=data['has_visual_preview'],
            default_params=data['default_params']
        )
        definitions_map[block_id] = definition

    # --- 2. PAGES ---

    # Hardcoding UUIDs for consistency with initial Vue app state
    PAGE_HOME_ID = uuid.UUID('f71d182e-9d2a-43f1-b4f0-32b7a950a120')
    PAGE_ABOUT_ID = uuid.UUID('322a012a-3e5f-4a3b-9a94-44b4c78a05f1')
    PAGE_BLOG_ID = uuid.UUID('7e7d692f-1a5c-4d8e-9c7f-02d2e1f4d9a3')


    page_home = Page.objects.create(
        id=PAGE_HOME_ID,
        title='Home',
        slug='/',
        status='published',
        layout='home',
        description='The main landing page for the site.',
        tags=['home', 'landing'],
        date='2023-10-15'
    )

    page_about = Page.objects.create(
        id=PAGE_ABOUT_ID,
        title='About Us',
        slug='/about',
        status='draft',
        layout='single',
        description='Learn more about our company.',
        tags=['about', 'company'],
        date='2023-11-01'
    )

    page_blog = Page.objects.create(
        id=PAGE_BLOG_ID,
        title='Blog',
        slug='/blog',
        status='published',
        layout='list',
        description='Our latest thoughts and updates.',
        tags=['blog', 'news'],
        date='2023-09-20'
    )
    
    pages_map = {
        'p1': page_home,
        'p2': page_about,
        'p3': page_blog,
    }

    # --- 3. INITIAL BLOCK INSTANCE (Main Content for Home Page) ---

    # This mirrors the single hero block initially present on the 'Home' page (p1)
    BlockInstance.objects.create(
        id=uuid.UUID('088b901a-8537-4148-9c59-a29e469d724b'), # Arbitrary UUID
        definition=definitions_map['hero'],
        page=page_home,
        zone='main',
        sort_order=0,
        params={
            'title': 'Build Faster',
            'subtitle': 'The ultimate Hugo CMS editor.',
            'bgImage': 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&q=80'
        }
    )

def reverse_initial_data(apps, schema_editor):
    """
    Reverses the data creation by deleting all entries based on the primary keys/IDs
    """
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    Page = apps.get_model('hugo', 'Page')
    BlockInstance = apps.get_model('hugo', 'BlockInstance')

    # Delete instances first (due to FK constraints)
    BlockInstance.objects.all().delete()
    
    # Delete pages
    Page.objects.filter(id__in=[
        'f71d182e-9d2a-43f1-b4f0-32b7a950a120',
        '322a012a-3e5f-4a3b-9a94-44b4c78a05f1',
        '7e7d692f-1a5c-4d8e-9c7f-02d2e1f4d9a3',
    ]).delete()

    # Delete block definitions
    BlockDefinition.objects.filter(id__in=BLOCK_DEFINITIONS_DATA.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0001_initial'), # Assuming your previous migration that created models
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]