# Generated by Django 5.2.8 on 2025-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.CharField(help_text="Unique key like 'home' or 'list'", max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Human-readable name like 'Home Page'", max_length=100)),
                ('zones', models.JSONField(default=list, help_text="Array of zone names like ['header', 'main', 'footer']")),
                ('description', models.TextField(blank=True, help_text='Optional description for admin UI')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
