# Generated by Django 5.2.8 on 2025-11-26 18:51

from django.db import migrations


def convert_zones_to_config(apps, schema_editor):
    """Convert simple zone arrays to detailed zone config objects."""
    LayoutTemplate = apps.get_model('hugo', 'LayoutTemplate')
    
    # Default zone configurations
    zone_defaults = {
        'header': {'name': 'header', 'width': 'w-full', 'order': 0, 'cssClasses': 'bg-slate-50/50'},
        'sidebar': {'name': 'sidebar', 'width': 'w-64', 'order': 1, 'cssClasses': 'border-r border-slate-100 bg-slate-50/30'},
        'main': {'name': 'main', 'width': 'flex-1', 'order': 2, 'cssClasses': 'min-h-[400px]'},
        'footer': {'name': 'footer', 'width': 'w-full', 'order': 3, 'cssClasses': 'bg-slate-50/50'},
    }
    
    for layout in LayoutTemplate.objects.all():
        if layout.zones and isinstance(layout.zones, list) and len(layout.zones) > 0:
            # Check if already converted (first item is a dict)
            if isinstance(layout.zones[0], dict):
                continue
            
            # Convert simple array to config objects
            new_zones = []
            for zone_name in layout.zones:
                if zone_name in zone_defaults:
                    new_zones.append(zone_defaults[zone_name].copy())
            
            layout.zones = new_zones
            layout.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0003_layouttemplate'),
    ]

    operations = [
        migrations.RunPython(convert_zones_to_config, reverse_code=migrations.RunPython.noop),
    ]
