# Generated by Django 5.2.8 on 2025-12-01 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0004_convert_zones_to_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(help_text="URL slug for the website (e.g., 'my-site')", max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='layouttemplate',
            name='zones',
            field=models.JSONField(default=list, help_text="Array of zone configs: [{'name': 'header', 'width': 'w-full', 'order': 0, 'cssClasses': ''}]. Supported widths: 'w-64' (fixed), 'flex-1' (flexible), 'w-full' (full width). Order controls display sequence in flex container."),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(help_text="URL path (e.g., '/about')", max_length=200),
        ),
        migrations.AddField(
            model_name='blockinstance',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hugo.website'),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='hugo.website'),
        ),
    ]
