# Generated by Django 5.2.8 on 2025-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0005_website_alter_layouttemplate_zones_alter_page_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful publish', null=True),
        ),
    ]
