# Generated by Django 5.2.8 on 2025-12-01 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0006_add_last_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('local', 'Local Filesystem'), ('s3', 'S3 Compatible Storage')], default='local', max_length=20)),
                ('s3_bucket', models.CharField(blank=True, max_length=200)),
                ('s3_endpoint', models.CharField(blank=True, help_text='e.g., https://nyc3.digitaloceanspaces.com', max_length=200)),
                ('s3_access_key', models.CharField(blank=True, max_length=200)),
                ('s3_secret_key', models.CharField(blank=True, max_length=200)),
                ('s3_region', models.CharField(blank=True, max_length=100)),
                ('s3_public_url', models.CharField(blank=True, help_text='Base URL for public access (CDN)', max_length=200)),
                ('local_media_path', models.CharField(default='media/uploads', help_text='Directory to store files', max_length=200)),
                ('local_public_url', models.CharField(default='/media/', help_text='URL prefix for local files', max_length=200)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to='hugo.website')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Relative path in storage', max_length=500)),
                ('file_url', models.CharField(help_text='Publicly accessible URL', max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hugo.website')),
            ],
        ),
    ]
