# Generated by Django 5.2.8 on 2025-12-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0008_update_block_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Global CSS for the website', null=True),
        ),
        migrations.AlterField(
            model_name='storagesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
