# Generated by Antigravity

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0010_add_deployment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentprovider',
            name='cf_zone_id',
            field=models.CharField(blank=True, help_text='Cloudflare Zone ID for monu.dev domain', max_length=200),
        ),
    ]
