# Generated by Antigravity

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0011_add_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentprovider',
            name='website',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_provider', to='hugo.website'),
        ),
    ]
