# Generated by Antigravity

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0012_allow_global_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentprovider',
            name='name',
            field=models.CharField(default='New Provider', max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='deployment_provider',
            field=models.ForeignKey(blank=True, help_text='Deployment configuration for this website', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='hugo.deploymentprovider'),
        ),
    ]
