# Generated by Antigravity

from django.db import migrations

def migrate_providers(apps, schema_editor):
    DeploymentProvider = apps.get_model('hugo', 'DeploymentProvider')
    Website = apps.get_model('hugo', 'Website')
    
    for provider in DeploymentProvider.objects.all():
        if provider.website:
            # It's a site-specific provider
            provider.name = f"Provider for {provider.website.name}"
            provider.save()
            
            # Link website to provider
            website = provider.website
            website.deployment_provider = provider
            website.save()
        else:
            # It's a global provider
            provider.name = "Global Default"
            provider.save()

def reverse_migrate(apps, schema_editor):
    # No easy reverse for this logic without losing the decoupling
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0013_add_reusable_providers'),
    ]

    operations = [
        migrations.RunPython(migrate_providers, reverse_migrate),
    ]
