# Generated by Antigravity

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0014_migrate_provider_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentprovider',
            name='website',
        ),
    ]
