# Generated by Django 5.2.8 on 2025-12-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0015_remove_website_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='deployment_provider',
        ),
        migrations.DeleteModel(
            name='DeploymentHistory',
        ),
        migrations.DeleteModel(
            name='DeploymentProvider',
        ),
    ]
