# Generated by Django 5.2.8 on 2025-12-03 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0016_remove_website_deployment_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Provider', max_length=200)),
                ('provider_type', models.CharField(choices=[('cloudflare_r2', 'Cloudflare R2'), ('netlify', 'Netlify'), ('vercel', 'Vercel')], default='cloudflare_r2', max_length=50)),
                ('enabled', models.BooleanField(default=False, help_text='Enable automatic deployment on publish')),
                ('cf_account_id', models.CharField(blank=True, help_text='Cloudflare Account ID', max_length=200)),
                ('cf_zone_id', models.CharField(blank=True, help_text='Cloudflare Zone ID for monu.dev domain', max_length=200)),
                ('cf_r2_access_key', models.CharField(blank=True, help_text='R2 Access Key ID', max_length=200)),
                ('cf_r2_secret_key', models.CharField(blank=True, help_text='R2 Secret Access Key', max_length=200)),
                ('cf_api_token', models.CharField(blank=True, help_text='Cloudflare API Token for domain config', max_length=200)),
                ('cf_bucket_name', models.CharField(blank=True, help_text='R2 Bucket Name', max_length=200)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain (e.g., mysite.monu.dev)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deployment Provider',
                'verbose_name_plural': 'Deployment Providers',
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('uploading', 'Uploading'), ('configuring', 'Configuring Domain'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('deployment_url', models.URLField(blank=True, help_text='URL where the site is deployed', null=True)),
                ('hugo_version', models.CharField(blank=True, max_length=50)),
                ('build_duration_seconds', models.FloatField(blank=True, null=True)),
                ('files_uploaded', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('build_output', models.TextField(blank=True, help_text='Hugo build output logs')),
                ('deployment_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='hugo.website')),
                ('deployment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='hugo.deploymentprovider')),
            ],
            options={
                'verbose_name': 'Deployment History',
                'verbose_name_plural': 'Deployment Histories',
                'ordering': ['-started_at'],
            },
        ),
    ]
