# Generated by Django 5.2.8 on 2025-12-03 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0017_deploymentprovider_deploymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='deployment_provider',
            field=models.ForeignKey(blank=True, help_text='Deployment configuration for this website', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='hugo.deploymentprovider'),
        ),
    ]
