# Generated by Django 5.2.8 on 2025-12-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0018_website_deployment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentprovider',
            name='pages_project_name',
            field=models.CharField(blank=True, help_text='Pages project name (optional, auto-generated if empty)', max_length=200),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='cf_api_token',
            field=models.CharField(blank=True, help_text='Cloudflare API Token with Pages and DNS permissions', max_length=200),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='cf_bucket_name',
            field=models.CharField(blank=True, help_text='[Legacy] R2 Bucket Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='cf_r2_access_key',
            field=models.CharField(blank=True, help_text='[Legacy] R2 Access Key ID', max_length=200),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='cf_r2_secret_key',
            field=models.CharField(blank=True, help_text='[Legacy] R2 Secret Access Key', max_length=200),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='cf_zone_id',
            field=models.CharField(blank=True, help_text='[Legacy] Cloudflare Zone ID', max_length=200),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Base custom domain (e.g., monu.dev)', max_length=200),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='provider_type',
            field=models.CharField(choices=[('cloudflare_pages', 'Cloudflare Pages'), ('cloudflare_r2', 'Cloudflare R2 (Legacy)'), ('netlify', 'Netlify'), ('vercel', 'Vercel')], default='cloudflare_pages', max_length=50),
        ),
    ]
