# Generated by Django 5.2.8 on 2025-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0023_core_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockdefinition',
            name='is_container',
            field=models.BooleanField(default=False, help_text='Can this block contain other blocks?'),
        ),
        migrations.AddField(
            model_name='blockdefinition',
            name='schema',
            field=models.JSONField(default=dict, help_text='JSON Schema defining the fields (title, type, default, etc.)'),
        ),
        migrations.AlterField(
            model_name='deploymentprovider',
            name='cf_zone_id',
            field=models.CharField(blank=True, help_text='Cloudflare Zone ID (for custom domain DNS)', max_length=200),
        ),
    ]
