# Generated by Django 5.0.1 on 2024-12-08
from django.db import migrations


def create_brand_logo_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    
    BlockDefinition.objects.update_or_create(
        id='brand_logo',
        defaults={
            'label': 'Brand Logo',
            'icon': 'building',
            'has_visual_preview': True,
            'default_params': {
                'logo_image': '',
                'brand_name': 'Brand Name',
                'tagline': 'Your tagline here',
                'link_url': '/',
                'logo_size': '80'
            },
            'schema': {
                'type': 'object',
                'properties': {
                    'logo_image': {
                        'type': 'string',
                        'format': 'uri',
                        'label': 'Logo Image URL'
                    },
                    'brand_name': {
                        'type': 'string',
                        'label': 'Brand Name'
                    },
                    'tagline': {
                        'type': 'string',
                        'label': 'Tagline'
                    },
                    'link_url': {
                        'type': 'string',
                        'label': 'Link URL',
                        'default': '/'
                    },
                    'logo_size': {
                        'type': 'string',
                        'label': 'Logo Size (px)',
                        'default': '80'
                    }
                }
            }
        }
    )


def reverse_brand_logo_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    BlockDefinition.objects.filter(id='brand_logo').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0032_carousel_container'),
    ]

    operations = [
        migrations.RunPython(create_brand_logo_block, reverse_brand_logo_block),
    ]
