# Generated by Django 5.0.1 on 2024-12-08
from django.db import migrations


def create_button_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    
    BlockDefinition.objects.update_or_create(
        id='button',
        defaults={
            'label': 'Button',
            'icon': 'square',
            'has_visual_preview': True,
            'default_params': {
                'text': 'Click Here',
                'url': '/',
                'style': 'primary',
                'size': 'medium',
                'full_width': False,
                'new_tab': False
            },
            'schema': {
                'type': 'object',
                'properties': {
                    'text': {
                        'type': 'string',
                        'label': 'Button Text'
                    },
                    'url': {
                        'type': 'string',
                        'label': 'Link URL',
                        'description': 'Page path (e.g. /about) or external URL (https://...)'
                    },
                    'style': {
                        'type': 'string',
                        'label': 'Style',
                        'enum': ['primary', 'secondary', 'outline', 'ghost'],
                        'default': 'primary'
                    },
                    'size': {
                        'type': 'string',
                        'label': 'Size',
                        'enum': ['small', 'medium', 'large'],
                        'default': 'medium'
                    },
                    'full_width': {
                        'type': 'boolean',
                        'label': 'Full Width',
                        'default': False
                    },
                    'new_tab': {
                        'type': 'boolean',
                        'label': 'Open in New Tab',
                        'default': False
                    }
                }
            }
        }
    )


def reverse_button_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    BlockDefinition.objects.filter(id='button').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0033_add_brand_logo_block'),
    ]

    operations = [
        migrations.RunPython(create_button_block, reverse_button_block),
    ]
