# Generated by Django 5.0.1 on 2024-12-08
from django.db import migrations


def update_row_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    
    row = BlockDefinition.objects.get(id='row')
    row.schema = {
        'type': 'object',
        'properties': {
            'cols': {'type': 'string', 'label': 'Columns', 'default': '1'},
            'md_cols': {'type': 'string', 'label': 'Columns (md+)', 'default': '2'},
            'gap': {'type': 'string', 'label': 'Gap', 'default': '4'},
            'justify': {
                'type': 'string',
                'label': 'Justify Content',
                'enum': ['start', 'center', 'end', 'between', 'around', 'evenly'],
                'default': 'start'
            },
            'align': {
                'type': 'string',
                'label': 'Align Items',
                'enum': ['start', 'center', 'end', 'stretch'],
                'default': 'stretch'
            },
            'class': {'type': 'string', 'label': 'CSS Classes', 'default': ''}
        }
    }
    row.default_params = {
        'cols': '1',
        'md_cols': '2',
        'gap': '4',
        'justify': 'start',
        'align': 'stretch',
        'class': ''
    }
    row.save()


def reverse_row_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    row = BlockDefinition.objects.get(id='row')
    row.schema = {
        'type': 'object',
        'properties': {
            'cols': {'type': 'string', 'default': '1'},
            'md_cols': {'type': 'string', 'default': '2'},
            'gap': {'type': 'string', 'default': '4'},
            'class': {'type': 'string', 'default': ''}
        }
    }
    row.default_params = {'cols': '1', 'md_cols': '2', 'gap': '4', 'class': ''}
    row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0034_add_button_block'),
    ]

    operations = [
        migrations.RunPython(update_row_block, reverse_row_block),
    ]
