# Generated by Django 5.2.8 on 2025-12-09 14:12

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0036_canonical_blocks'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetemplate',
            name='category',
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='placeholder_schema',
            field=models.JSONField(default=dict, help_text="Schema defining placeholders LLM should fill: {business_name: 'text', tagline: 'text', ...}"),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tags for template categorization and LLM selection', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='sitetemplate',
            name='id',
            field=models.CharField(help_text="URL-friendly identifier (e.g., 'modern-therapist', 'food-truck-basic')", max_length=50, primary_key=True, serialize=False),
        ),
    ]
