# Generated by Django 5.2.8 on 2025-12-09 14:17

import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0038_charfieldtaggeditem_alter_sitetemplate_tags_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='slug',
            field=models.SlugField(default='default-template', help_text="URL-friendly identifier (e.g., 'modern-therapist', 'food-truck-basic')", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitetemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitetemplate',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tags for template categorization and LLM selection', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
