# Generated by Django 5.2.8 on 2025-12-09 14:19

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0039_sitetemplate_slug_alter_sitetemplate_id_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetemplate',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tags for template categorization and LLM selection', through='hugo.CharFieldTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
