# Generated by Django 5.2.8 on 2025-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0040_alter_sitetemplate_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTag',
            fields=[
                ('name', models.SlugField(help_text="Slug-style tag name (e.g., 'therapy', 'food-truck')", primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Human-readable label', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.RemoveField(
            model_name='sitetemplate',
            name='tags',
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='tags',
            field=models.JSONField(default=list, help_text='List of tag names for template categorization and LLM selection'),
        ),
    ]
