# Generated by Django 5.2.8 on 2025-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0041_templatetag_remove_sitetemplate_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='theme_preset',
            field=models.CharField(default='default', help_text='The theme engine this template is optimized for.', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_preset',
            field=models.CharField(default='default', help_text="Active theme engine (e.g., 'default', 'daisy', 'preline')", max_length=50),
        ),
    ]
