# Generated by Django

from django.db import migrations

def add_navbar_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    
    navbar_block = {
        'id': 'navbar',
        'label': 'Navbar',
        'icon': 'menu',
        'is_container': True,
        'default_params': {
            'justify': 'between',
            'align': 'center',
            'gap': '0'
        },
        'schema': {
            'fields': [
                {'name': 'justify', 'type': 'select', 'label': 'Justify Content', 
                 'options': ['start', 'center', 'end', 'between', 'around', 'evenly']},
                {'name': 'align', 'type': 'select', 'label': 'Align Items',
                 'options': ['start', 'center', 'end', 'stretch']},
                {'name': 'gap', 'type': 'select', 'label': 'Gap',
                 'options': ['0', '1', '2', '4', '6', '8']}
            ]
        }
    }
    
    BlockDefinition.objects.update_or_create(
        id=navbar_block['id'],
        defaults={
            'label': navbar_block['label'],
            'icon': navbar_block['icon'],
            'is_container': navbar_block['is_container'],
            'default_params': navbar_block['default_params'],
            'schema': navbar_block['schema']
        }
    )

def remove_navbar_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    BlockDefinition.objects.filter(id='navbar').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0043_update_hero_block'),
    ]

    operations = [
        migrations.RunPython(add_navbar_block, remove_navbar_block),
    ]
