# Generated by Django

from django.db import migrations

def update_navbar_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    
    try:
        navbar = BlockDefinition.objects.get(id='navbar')
        
        # Add position and opacity fields to schema
        navbar.schema['fields'].extend([
            {
                'name': 'position',
                'type': 'select',
                'label': 'Position Type',
                'options': ['inline', 'sticky', 'overlayed']
            },
            {
                'name': 'opacity',
                'type': 'range',
                'label': 'Opacity',
                'min': 0,
                'max': 100,
                'step': 5
            }
        ])
        
        # Update default params
        navbar.default_params['position'] = 'inline'
        navbar.default_params['opacity'] = 100
        
        navbar.save()
    except BlockDefinition.DoesNotExist:
        pass

def reverse_update_navbar_block(apps, schema_editor):
    BlockDefinition = apps.get_model('hugo', 'BlockDefinition')
    
    try:
        navbar = BlockDefinition.objects.get(id='navbar')
        
        # Remove position and opacity fields
        navbar.schema['fields'] = [
            field for field in navbar.schema['fields']
            if field['name'] not in ['position', 'opacity']
        ]
        
        # Remove from default params
        navbar.default_params.pop('position', None)
        navbar.default_params.pop('opacity', None)
        
        navbar.save()
    except BlockDefinition.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0044_add_navbar_block'),
    ]

    operations = [
        migrations.RunPython(update_navbar_block, reverse_update_navbar_block),
    ]
