# Generated by Django 4.2.27 on 2025-12-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0045_add_navbar_position_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order in the sidebar'),
        ),
        migrations.AlterField(
            model_name='website',
            name='theme_preset',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('cupcake', 'Cupcake'), ('corporate', 'Corporate'), ('retro', 'Retro'), ('cyberpunk', 'Cyberpunk'), ('valentine', 'Valentine'), ('halloween', 'Halloween'), ('garden', 'Garden'), ('forest', 'Forest'), ('aqua', 'Aqua'), ('lofi', 'Lo-Fi'), ('pastel', 'Pastel'), ('fantasy', 'Fantasy'), ('wireframe', 'Wireframe'), ('black', 'Black'), ('luxury', 'Luxury'), ('dracula', 'Dracula'), ('cmyk', 'CMYK'), ('autumn', 'Autumn'), ('business', 'Business'), ('acid', 'Acid'), ('lemonade', 'Lemonade'), ('night', 'Night'), ('coffee', 'Coffee'), ('winter', 'Winter')], default='light', help_text='DaisyUI theme for the website', max_length=50),
        ),
    ]
