# Generated by Django 4.2.27 on 2025-12-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0047_add_menu_position_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentprovider',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Make this the default provider for new websites'),
        ),
    ]
